# Configuration Render.com pour le déploiement du backend Django
# Documentation : https://render.com/docs/deploy-django

services:

  - type: web
    name: detectioncancer-backend
    runtime: python
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application --chdir backend --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: MEDIA_URL
        value: /media/
      - key: MEDIA_ROOT
        value: media
      - key: OAUTH2_PROVIDER_ACCESS_TOKEN_EXPIRE_SECONDS
        value: 36000
      - key: OAUTH2_PROVIDER_REFRESH_TOKEN_EXPIRE_SECONDS
        value: 1209600
    plan: free
    autoDeploy: true
