# Generated by Django 5.2.3 on 2025-07-27 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0004_add_patients"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamenMedical",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("patient", models.CharField(max_length=128)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mammographie", "Mammographie"),
                            ("biopsie", "Biopsie"),
                        ],
                        max_length=32,
                    ),
                ),
                ("date", models.DateField()),
                ("score_ia", models.FloatField(blank=True, null=True)),
                ("findings", models.TextField(blank=True)),
                ("advice", models.TextField(blank=True)),
                ("interpretation", models.TextField(blank=True)),
                ("rapport_url", models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="biopsyreport",
            name="patient",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="biopsyreport",
            name="resultat",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="medecin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"profile__role": "medecin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TransfertPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("motif", models.CharField(blank=True, max_length=256)),
                (
                    "medecin_cible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferts_cible",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medecin_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferts_source",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferts_patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
