# Generated by Django 5.2.3 on 2025-07-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0005_examenmedical_biopsyreport_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="urgence",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
